x-shared-env: &shared-api-worker-env
  CONSOLE_API_URL: ${CONSOLE_API_URL}
  APP_API_URL: ${APP_API_URL}
  SENTRY_DSN: ${SENTRY_DSN}

services:
  prod-web:
    image: langgenius/dify-web:0.6.12-fix1
    container_name: prod-dify-web
    restart: always
    environment:
      CONSOLE_API_URL: ${CONSOLE_API_URL:-}
      APP_API_URL: ${APP_API_URL:-}
      SENTRY_DSN: ${SENTRY_DSN:-}

  # The nginx reverse proxy.
  # used for reverse proxying the API service and Web service.
  prod-nginx:
    image: nginx:latest
    container_name: prod-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      #- ./nginx/ssl:/etc/ssl
    ports:
      - "8012:80"
networks:
  # create a network between sandbox, api and ssrf_proxy, and can not access outside.
  ssrf_proxy_network:
    driver: bridge
    internal: true

#volumes:
#  oradata:
